import 'package:shove/puzzles/shove_puzzle.dart';

/// Puzzles ordered from easy to hard. Each one has a single winning first move.
const shovePuzzles = <ShovePuzzle>[
  ShovePuzzle(
    title: 'Hop to the goal',
    hint: 'A shover can hop forward over a friendly leaper.',
    movesToWin: 1,
    layout: [
      '........',
      '.....L..',
      '.....S..',
      '.t......',
      '.s......',
      '........',
      '..S.....',
      '....b...',
    ],
  ),
  ShovePuzzle(
    title: 'Charge!',
    hint:
        'A charger sends an enemy as far back as it will go. '
        'Without shovers the opponent cannot win.',
    movesToWin: 1,
    layout: [
      '......b.',
      '.t......',
      '...s....',
      '........',
      '........',
      '........',
      '...C..S.',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Over the edge',
    hint: 'Shovers can shove sideways too. The edge of the board is no friend.',
    movesToWin: 1,
    layout: [
      '........',
      '..b...l.',
      '........',
      '........',
      'sS......',
      '........',
      '......T.',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Make room',
    hint: 'Your leaper can step in front of your shover to give it a hop.',
    movesToWin: 2,
    layout: [
      '..s.....',
      '........',
      '.....LS.',
      '......h.',
      '........',
      '........',
      '..T.....',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Reel it in',
    hint: 'A hook can pull an enemy shover right next to your own.',
    movesToWin: 2,
    layout: [
      '.......l',
      's.......',
      '.S......',
      'H.....c.',
      '........',
      '........',
      '....B..S',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Throwing practice',
    hint: 'Throw the enemy shover to a square beside your shover.',
    movesToWin: 2,
    layout: [
      '.b......',
      '........',
      's.......',
      'T.....t.',
      '.S......',
      '........',
      '......L.',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Frozen',
    hint: 'A player with no legal move loses, and stunned pieces cannot move.',
    movesToWin: 2,
    layout: [
      '........',
      '........',
      '....C.c.',
      '........',
      'L.s.....',
      '...S....',
      '........',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Shield',
    hint: 'An enemy cannot charge a piece that has a piece right behind it.',
    movesToWin: 3,
    layout: [
      '.....s..',
      '.....c..',
      '...S....',
      '..B.....',
      '........',
      '........',
      '........',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Stepping stone',
    hint: 'A leaper can leap over enemy pieces too, even blockers.',
    movesToWin: 3,
    layout: [
      's.......',
      '........',
      '....Lb..',
      '......S.',
      '........',
      '........',
      '........',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Quiet move',
    hint: 'Get your thrower into position before you throw.',
    movesToWin: 3,
    layout: [
      '......t.',
      '........',
      '........',
      '........',
      '.sT.....',
      '........',
      '.S......',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Sweep',
    hint: 'Your charger can travel the whole row.',
    movesToWin: 3,
    layout: [
      '........',
      '........',
      'H.sC...c',
      '........',
      '..S.....',
      '........',
      '.......T',
      '........',
    ],
  ),
  ShovePuzzle(
    title: 'Hooked',
    hint: 'A hook can pull an enemy charger too.',
    movesToWin: 3,
    layout: [
      '........',
      '..c.....',
      '...S....',
      '.....s..',
      '..H.....',
      '........',
      '........',
      '........',
    ],
  ),
];
